### ISSUE TITLE
Dynamically change body style

### ISSUE THREAD

**Issue by hazae41** [postui/aleph.js#10]
Hello, I'm trying to modify the `body` background when the user clicks a button.

However, it seems I cannot use the `document` keyword nor the `findDOMNode` method.

Is there a way to dynamically change the `body` background?

**Comment by hazae41** [comment]
Maybe we could have a React portal `<Body></Body>`

**Comment by ije** [comment]
you can using `window.document.body.style.backgroundColor = 'black'` or `window.document.body.className = 'dark'` just ignore the vscode error hits, or strip window types:
```typescript
const { document } = window as any
```
or add dom lib: 
```typescript
/// <reference lib="dom" />
```

**Comment by ije** [comment]
there is **a theme using example**, you can add it in you `app.tsx`:
```jsx
import React, { ComponentType, useCallback } from 'https://esm.sh/react'
import { Head } from 'https://deno.land/x/aleph/mod.ts'

export default function App({ Page, pageProps }: { Page: ComponentType<any>, pageProps: any }) {
  const setTheme = useCallback((theme: 'dark' | 'light') => {
    document.documentElement.classList.add(`${theme}-theme`);
  }, [])

  return (
    <>
      <Head>
        <script>{`
        try {
          var query = window.matchMedia("(prefers-color-scheme: dark)");
          if (query.matches) {
            document.documentElement.classList.add("dark-theme");
            document.documentElement.style.background = "#000";
          }
        } catch (e) {}
        `}</script>
      </Head>
      <Page {...pageProps} />
    </>
  )
}
```

**Comment by hazae41** [comment]
Thanks, I've done the following

```typescript
export interface Theme {
  background?: string
}

export function useTheme(init: Theme) {
  const $theme = useState(init)
  const [theme] = $theme

  useEffect(() => {
    const { document } = window as any
    const { body } = document

    const { background } = theme
    body.style.background = background
  }, [theme])
}
```

Maybe we could create a `<Body> </Body>` portal in order to do this quicker and safer?

**Comment by ije** [comment]
i think `useTheme` is the right way, `<Body>` sort of complex

**Comment by hazae41** [comment]
So I exported useTheme to another file and Deno linter throws no-explicit-any

It works fine in app.tsx but not in any other file ❓ 

Anyway, I added the following workaround

```typescript
// deno-lint-ignore no-explicit-any
const { document } = window as any
```
